### ISSUE TITLE
Questions about usage: where i put useScreens?

### ISSUE THREAD

**Issue by misaku** [kmagiera/react-native-screens#103]
if the path of my application is:

> App
__SRC
....... | ___ index.js
....... | ___ ROUTERS
.............. | ___ ra.js
.............. | ___ rb.js
.............. | ___ SUBROUTERS
..................... | ___ rc.js
..................... | ___ rd.js
....... | ___ PAGES
.............. | ___ p1.js
.............. | ___ p2.js
.............. | ___ p3.js
.............. | ___ p4.js
.............. | ___ p5.js
.............. | ___ p6.js

the questions are:
Should I put useScreens on just should.js?
Should I put useScreens on all routes and subroutines (ra.js, rb.js, rc.js, ...)?
Should I put useScreens on all pages (p1.js, p2.js, p3.js, ...)?

**Comment by joshjhargreaves** [comment]
You should call `useScreens()` once and at the top level of your application. So in your case I would put it in `index.js`. Technically it could be called at the top level of any file or module that's excecuted when JavaScript is first initialized on that first path as long as it is executed before any rendering happens.

All calling `useScreens` does it change a variable that affects how subsequent renders of navigators: `https://github.com/kmagiera/react-native-screens/blob/master/src/screens.native.js#L21`.
