### ISSUE TITLE
How do you verify this is working?

### ISSUE THREAD

**Issue by GollyJer** [kmagiera/react-native-screens#113]
I've followed the instructions to set up react-native-screens using `Expo` and `React Navigation`.

How do I verify it's working? 🤷‍♂️

Thanks! 👍

**Comment by rszalski** [comment]
@GollyJer You should be able to see the difference in memory usage & view hierarchy (complexity) on iOS if you compare before and after. See https://twitter.com/janicduplessis/status/1039979591815897088

**Comment by GollyJer** [comment]
Cool. Thanks!
