### ISSUE TITLE
[Android] Android X migration!

### ISSUE THREAD

**Issue by Twitchkidd** [kmagiera/react-native-screens#119]
Hi! I upgraded my rn59.9 app to rn 60, and the android build failed. After running the 'migrate to android x' thing from android studio, I changed the following files to fix it for me!

node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/LifecycleHelper.java
node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/Screen.java
node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java

support.annotation, arch.lifecycle, and the fragment stuff had to be changed, which I got from the android dev site: https://developer.android.com/jetpack/androidx/migrate

I don't know what to do now though! I've got them saved in a separate folder incase running yarn blows them away, and I'll paste here, but I haven't really contributed to open source before. Any hints?

Screen.java imports:

import android.annotation.SuppressLint;
import android.content.Context;
import android.graphics.Paint;
import android.os.Bundle;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import com.facebook.react.uimanager.PointerEvents;
import com.facebook.react.uimanager.ReactPointerEventsView;

ScreenContainer.java imports:

import android.content.Context;
import android.content.ContextWrapper;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentActivity;
import androidx.fragment.app.FragmentManager;
import androidx.fragment.app.FragmentTransaction;
import android.view.ViewGroup;
import android.view.ViewParent;

LifecycleHelper.java imports:

import androidx.lifecycle.Lifecycle;
import androidx.lifecycle.LifecycleObserver;
import androidx.fragment.app.Fragment;

import android.view.View;
import android.view.ViewParent;

import java.util.HashMap;
import java.util.Map;

import javax.annotation.Nullable;

**Comment by radeno** [comment]
You can use https://github.com/mikehardy/jetifier
RN 0.60 is backward incompatible with older RN. So If react-native-screens start supports new RN0.60, older RNs will not be supported.

**Comment by Twitchkidd** [comment]
OKAY so: My issue was in not understanding how to actually use jetifier, because I'd tried it, and when it didn't work, I was like uh-oh, and fixed things manually, which was fine for react-native-screens because there were like ten things to change or whatever, but in react-native-camera there were like fifty, and then you commented with that link, and it was like, well, another real person is suggesting this, so I looked at it and you have to run the steps in that order (which was not really clear when a list was given after the prompt, "How can you do it?") and the first step ("Convert your app to AndroidX via the standard AndroidX migration") really means to use the "Migrate to Android X" tool from Android Studio. SOOOO just do that, and by the way jetifier !== jetify. Yay.

**Comment by radeno** [comment]
@Twitchkidd anyway 1.0.0-alpha23 supports AndroidX. You can test it.
