### ISSUE TITLE
[iOS] RN v0.60 - Screen native module hasn't been linked.

### ISSUE THREAD

**Issue by codecog** [kmagiera/react-native-screens#125]
Created a fresh react native project and added react-navigation, react-native-gesture-handler & react-native-screens.

Added gesture handler and screens to the non auto linking config and did the appropriate `react-native link xxx` commands for both libraries. I then receive this error when loading the application:

<img width="377" alt="Screenshot 2019-07-10 17 01 07" src="https://user-images.githubusercontent.com/5106076/60984875-5028f880-a334-11e9-8e53-c3c1d28ab668.png">

**Comment by choibles** [comment]
Have you tried the following in Terminal?

`cd ios && pod install`

**Comment by rafael-arreola** [comment]
I have the same problem with android

**Comment by rafael-arreola** [comment]
perform the steps as mentioned in the other [thread](https://github.com/kmagiera/react-native-screens/issues/7), but still throw the error that he comments.

some way to fix it?

![Screenshot_2019-07-16_12-28-44](https://user-images.githubusercontent.com/6570453/61319893-813a7a80-a7c5-11e9-8966-1d0709195888.png)
![Screenshot_2019-07-16_12-29-44](https://user-images.githubusercontent.com/6570453/61319899-84356b00-a7c5-11e9-9f21-c46bb82d1dda.png)
![Screenshot_2019-07-16_12-30-11](https://user-images.githubusercontent.com/6570453/61319902-85ff2e80-a7c5-11e9-938a-5e03514238fd.png)

**Comment by jetobe95** [comment]
Same problem here

**Comment by code-freakz** [comment]
Works fine when switching off remote debugger.
But it should work with remote dubugger

**Comment by o5faruk** [comment]
Same problem, rn version 0.59.9, any solutions?

**Comment by herlarb** [comment]
Run `yarn add react-native-screens` directly as it appears that react-native 0.60 does not directly auto-link the react-native-screens dependency on react-navigation. The auto-link appears to only work if the 'react-native-screens' is found in the package.json.
For 0.59.*  you could use the "1.0.0-alpha.22" version  which works with the regular manual linking or use Jetify

**Comment by badgeek** [comment]
not working @herlarb

**Comment by brandtnewww** [comment]
Same problem here with Android. Fresh project!

```
"dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-screens": "^1.0.0-alpha.23",
    "react-native-unimodules": "0.4.0",
    "react-navigation": "^3.11.1"
}
```

**Comment by vikjovanov** [comment]
I had the same problem with iOs. 
I just launched `cd ios && pod install` and it's works perfectly now.

**Comment by sandyalta** [comment]
any solution about this for android with RN v.60?

**Comment by ckOfor** [comment]
Still a problem

**Comment by ckOfor** [comment]
I am using a fresh project and I have this problem

**Comment by tianlinzx** [comment]
I had the same problem with iOs.
I just launched cd ios && pod install and it's works perfectly now.

**Comment by codecog** [comment]
I think this has been solved and i'm going to close the issue. Working fine for me running a fresh project with the latest release.

**Comment by aaronkaz** [comment]
I have this issue on RN 0.61.5 with android.  Tried installing fresh, autolinking, manual-linking, nothing works.

**Comment by nateblog** [comment]
in your podfile just add

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

then pod install

it should work, I hate it but it seems not all RN Packages are autolinked

**Comment by UmairRehmat** [comment]
> perform the steps as mentioned in the other [thread](https://github.com/kmagiera/react-native-screens/issues/7), but still throw the error that he comments.
> 
> some way to fix it?
> 
> ![Screenshot_2019-07-16_12-28-44](https://user-images.githubusercontent.com/6570453/61319893-813a7a80-a7c5-11e9-8966-1d0709195888.png)
> ![Screenshot_2019-07-16_12-29-44](https://user-images.githubusercontent.com/6570453/61319899-84356b00-a7c5-11e9-9f21-c46bb82d1dda.png)
> ![Screenshot_2019-07-16_12-30-11](https://user-images.githubusercontent.com/6570453/61319902-85ff2e80-a7c5-11e9-938a-5e03514238fd.png)

@rafael-arreola did you find any solution so far? i am stuck on same issue

**Comment by amravazzi** [comment]
I have the same problem with android, react-native 0.59.10

**Comment by ashrafmakandar** [comment]
> I had the same problem with iOs. I just launched `cd ios && pod install` and it's works perfectly now.

For me deleting the app after installing pods and re running the app worked

**Comment by satyam9798** [comment]
1. If you have manually added enableScreens(true); in index.js remove it
2. pod install && delete the app in the simulator
3. npx react-native run-ios

And you'll be good to go!!
