### ISSUE TITLE
[Android] crashed at "react-native-screens": "^2.0.0-alpha.3"

### ISSUE THREAD

**Issue by lw1992** [kmagiera/react-native-screens#155]
hello ,
   when add "react-native-screens": "^2.0.0-alpha.3" to my app,
it always crashed when i open it . No warnings .

environment: android 9.0 / RN 0.60.5

**Comment by ghondar** [comment]
@lw1992 you need add in `android/app/build.gradle`
```
implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'
```
