### ISSUE TITLE
iOS: weird animation using createNativeStackNavigator

### ISSUE THREAD

**Issue by felippepuhle** [kmagiera/react-native-screens#163]
Just updated to `2.0.0-alpha.3` and started to use `createNativeStackNavigator`, but somehow the animation is weird... next screens seem to be transparent:

![bug](https://user-images.githubusercontent.com/15961929/65337420-78d43680-db9e-11e9-9bbc-8171bf55a49c.gif)

It should like this:

![right](https://user-images.githubusercontent.com/15961929/65337585-d36d9280-db9e-11e9-9792-450fdbb529f3.gif)

Any thoughts?

Thanks!

**Comment by felippepuhle** [comment]
Just noticed that a lot of screens seem to be mounted somehow (I have some videos and they still're playing after navigating), and `react-native-gesture-handler` started to crash.

I'll try to get more infos about it on monday.

Thanks!

**Comment by kmagiera** [comment]
I think this could be due a lack of default background set for the given screen. Pushed screen is transparent by default and only once the animation ends the screen below disappears making the window background visible. Can you try setting background color for the root component of the screen that you push?

**Comment by drewhamlett** [comment]
@kmagiera is right.  You need to set a backgroundColor.  I had to flex: 1 my container also.

**Comment by felippepuhle** [comment]
Sorry for the late response, I didn't notice the answer before.

I'll try to set a backgroundColor later on, but do you guys have any idea about the video stuff? With `2.0.0-alpha.3` some videos still playing even though the screen isn't focused anymore, is this a breaking change and I have to control on my side if video is paused based on router state?

Thank you

**Comment by satya164** [comment]
Setting background color fixes it, but there's also a similar issue when using large title. The title area has a transparent background too and it doesn't seem possible to set a background color for that.

**Comment by tobiaslins** [comment]
@satya164 I just figured out that setting `translucent: true` fixes the bug with the transparent background in the header while using large title! 😛

**Comment by felippepuhle** [comment]
I'm closing this as it can be solved with

```
    defaultNavigationOptions: {
      cardStyle: {
        backgroundColor: '#fff',
      },
    },
```

Please note that I'm using `^2.0.0-alpha.22` version
