### ISSUE TITLE
createNativeStackNavigator incompatible with react-navigation-stack 2.0 alpha

### ISSUE THREAD

**Issue by Ashoat** [kmagiera/react-native-screens#173]
It [imports `ScenesReducer`](https://github.com/kmagiera/react-native-screens/blob/master/createNativeStackNavigator.js#L11), which is [no longer exported](https://github.com/react-navigation/stack/blob/master/src/index.tsx). `react-navigation-stack` 2.0 is still in alpha, but I figured I'd open an issue to track.

**Comment by satya164** [comment]
imo the navigator shouldn't depend on `react-navigation-stack`. depending on a whole library and all the stuff associated with it (reanimated, rngh, safe area context, masked-view) etc. is a bit too much imo.

**Comment by Ashoat** [comment]
Worth noting that `react-native-screens` doesn't have an explicit `dependency` (or even `peerDependency`) on `react-navigation-stack`. There's just an implicit assumption that if you `import 'react-native-screens/createNativeStackNavigator'`, that you already have a `react-navigation-stack`. (Which is part of the reason it breaks when the user is using `react-navigation-stack@2` - the dependency version isn't explicitly specified.)

Thanks for #174, I think it makes a lot of sense, and didn't expect it would be that easy.
