### ISSUE TITLE
Breaks react-navigation drawer navigator on Android

### ISSUE THREAD

**Issue by teod** [kmagiera/react-native-screens#18]
This fails intermittently on Android, when the Drawer action to open is dispatched, the screen hangs with just the drawer overlay without Drawer actually being opened.

**Comment by fangasvsass** [comment]
I hit this issue too

**Comment by Unforgiven-wanda** [comment]
Same issue. I'm gonna hold off on adding this until this is resolved.

**Comment by brentvatne** [comment]
you can install the latest alpha version of react-navigation-drawer and import from that instead of directly from react-navigation. it uses react-native-gesture-handler and fixes this issue

**Comment by teod** [comment]
@brentvatne even though that solution fixed the issue from the subject, it actually caused me more issues with instances of the whole app remaining in an unresponsive state both on iOS and Android.

**Comment by brentvatne** [comment]
@teod - you'll need to post a link to a repo that reproduces the problem

**Comment by brentvatne** [comment]
when you get a chance please create an issue on https://github.com/react-navigation/react-navigation-drawer with a reproducible example - thanks

**Comment by outaTiME** [comment]
Same here with Expo SDK 31, 
it happens randomly on android i will try with the last version of  react-navigation-drawer, 

Thanks !!!

**Comment by brentvatne** [comment]
@outaTiME - try updating to the latest rc https://reactnavigation.org/blog/2018/11/01/react-navigation-3.0-rc.html
