### ISSUE TITLE
enableScreens is not a function

### ISSUE THREAD

**Issue by Jason6809** [kmagiera/react-native-screens#181]
enableScreens is not a function, someone help why is this happening wasn't this is suppose to be easy to use?

And screen is blank no matter how many time reload

**Comment by gabrielbull** [comment]
Documentation is ahead of release. You can use the legacy `useScreens` instead.

**Comment by njacob1001** [comment]
you should to use `useScreens`, but `enableScreens` is in the docs, why?

**Comment by gabrielbull** [comment]
I just why, the doc is ahead of the release.

**Comment by makarkotlov** [comment]
> Documentation is ahead of release. You can use the legacy `useScreens` instead.

I did as you said and got build failed in iOS simulator "Screen native module hasn't been linked" but I linked it!
![image](https://user-images.githubusercontent.com/32848434/67835990-726d9e80-fafc-11e9-9256-d4c1af050e3d.png)

**Comment by gabrielbull** [comment]
@makarkotlov thats a different issue, you should open a new issue if it persists. But basically, it didn’t link properly so maybe you should try the steps again?

**Comment by osdnk** [comment]
Released a new version
