### ISSUE TITLE
RNScreens.podspec isn't published to npm

### ISSUE THREAD

**Issue by AndrewJack** [kmagiera/react-native-screens#2]
The RNScreens.podspec isn't published to npm

1. Download - https://registry.npmjs.com/react-native-screens/-/react-native-screens-1.0.0-alpha.6.tgz
2. Extract
3. Check directory for  `RNScreens.podspec` file

![screen shot 2018-09-09 at 12 17 13](https://user-images.githubusercontent.com/798942/45263896-599eb700-b42a-11e8-8197-0b09059b4287.png)

**Comment by kmagiera** [comment]
Thanks @AndrewJack for noting. Added that to whitelist in package.json and published alpha.9 version which includes it
