### ISSUE TITLE
Unable to access copy/paste in TextInput [Android]

### ISSUE THREAD

**Issue by tombarton** [kmagiera/react-native-screens#210]
Copy/paste appears to be breaking in Android when `react-native-screens` is used with `react-navigation` 4.0.10. I've replicated the issue using React Navigation's "Get Started" example in both Expo snack and a standalone repo.

Versions:

```
"react": "16.8.3",
"react-native": "0.60.5",
"react-native-gesture-handler": "1.3.0",
"react-native-screens": "^2.0.0-alpha.7",
"react-navigation": "4.0.10",
"react-navigation-stack": "1.9.3"
```

Replicable repo:

Expo Snack: https://snack.expo.io/@tombarton/react-native-screens-copy-paste-android
GitHub Repo: https://github.com/tombarton/react-native-screens-copy-paste

**Comment by jemmyphan** [comment]
can confirm that this issue happened to us too.
to put more detail, text selection is not working on ```TextInput``` inside ```ScrollView```.
It's working just fine inside ```View```.

**Comment by ovy9086** [comment]
yes. this also breaks Android auto-fill for `TextInputs` that contain `autoCompleteTypes` like :

**Comment by ovy9086** [comment]
can somebody point us in the right direction here ? what can possibly cause this ? @kmagiera , willing to help , but not really sure where to start.

**Comment by compojoom** [comment]
I think that this is the same issue as this one: https://github.com/kmagiera/react-native-screens/issues/205

**Comment by kmagiera** [comment]
Thanks for pointing this out @compojoom. I'm closing this as a duplicate and lets track this issue on #205
