### ISSUE TITLE
Not able to do iOS 13 build

### ISSUE THREAD

**Issue by hntddt123** [kmagiera/react-native-screens#246]
Error message is 
fatal error: 'React/RCTRootContentView.h' file not found
#import <React/RCTRootContentView.h>

RNSScreenStack.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

**Comment by hntddt123** [comment]
Found solution myself 
Change
#import <React/RCTRootContentView.h>
To
#import "RCTRootContentView.h"

**Comment by suwu150** [comment]
这个问题在后期版本中解决了吗
