### ISSUE TITLE
createNativeStackNavigator not working correctly on android

### ISSUE THREAD

**Issue by Hirbod** [kmagiera/react-native-screens#257]
I have a pretty "big" navigation stack, which works absolutely perfect on iOS and feels so incredibly smooth right now. I am very happy. Unfortunately, it is not working perfectly on android.

```js
const timelineStack = createNativeStackNavigator({
    Timeline: {screen: Timeline},
    Story: {screen: Story},
}, StackNavigatorOptions);

const messagesStack = createNativeStackNavigator({
    Messages: {screen: Messages},
}, StackNavigatorOptions);

const profileStack = createNativeStackNavigator({
    Profile: {screen: Profile},
    EditProfile: {screen: EditProfile},
    AddCar: {screen: AddCar},
    Account: {screen: Account},
    EditAccount: {screen: EditAccount},
    Blocked: {screen: Blocked},
    SelectVehicle: {screen: SelectVehicle},
    SelectMake: {screen: SelectMake},
    SelectModel: {screen: SelectModel},
    SelectType: {screen: SelectType},
    SelectEngine: {screen: SelectEngine},
    SelectPicture: {screen: SelectPicture},

}, StackNavigatorOptions);

const messageStack = createNativeStackNavigator({
    Message: {screen: Message},
}, StackNavigatorOptions);

const userStack = createNativeStackNavigator({
        User: {screen: User},
        UserImage: {screen: UserImage},
    },
    {
        ...StackNavigatorOptions,
        transparentCard: true,
        cardStyle: {
            backgroundColor: "transparent"
        },
        transitionConfig: () => springyFadeIn(),
    },
);

const storyStack = createNativeStackNavigator({
    AddStory: {screen: AddStory},
}, {...StackNavigatorOptions, navigationOptions: { gesturesEnabled: false }});

const TabNavigator = createMaterialTopTabNavigator({
    Timeline: timelineStack,
    Messages: messagesStack,
    Profile: profileStack
}, TabNavigatorOptions(tabs));


const AppNavigator = createNativeStackNavigator({
    Home: TabNavigator,
    Message: messageStack,
    User: userStack,
}, StackNavigatorOptions);


export const SocialNavigator = createNativeStackNavigator(
    {
        Home: AppNavigator,
        AddStory: storyStack
    },
    {
        transparentCard: false,
        mode: 'modal',
        headerMode: 'none',
    }
);
```

Everything works as expect on iOS and on Android, but Android can't push/navigate to Screen "Message" and to screen "User" and "AddStory".

I added those as single stacks because they don't belong to any tab and they have to be pushable/navigateable from everywhere.

It has nothing to do with the cardStyle or anything else, I tried it naked (as "Message" (not Message*s*) is also a usual stack without any special settings). I know, its pretty encapsulated but it should also work on Android, since it works as expected on iOS. 

When I set "User" and "Message" to "createStackNavigator", they open as expected but the app crash on back handler/pop/goBack

**Comment by Hirbod** [comment]
@kmagiera this is my current and only working workaround

```js
const AppNavigator = ((Platform.OS === "ios") ? createNativeStackNavigator : createStackNavigator) ({
    Home: TabNavigator,
    Message: messageStack,
    User: userStack,
}, StackNavigatorOptions);


export const SocialNavigator = ((Platform.OS === "ios") ? createNativeStackNavigator : createStackNavigator) (
    {
        Home: AppNavigator,
        AddStory: storyStack
    },
    {
        transparentCard: false,
        mode: 'modal',
        headerMode: 'none',
    }
);
```

Is there any other solution?  Any help is highly appreciated. Thanks for your incredible work!

**Comment by Hirbod** [comment]
Well, looking through the commits, it looks like this has (or might be) fixed on alpha.22. As I am using Expo, I'm stuck now. Let's hope that Expo drops some quick updates here...

**Comment by Hirbod** [comment]
Closing this since this is fixed with alpha.13 (verified it myself)

**Comment by tevonsb** [comment]
Ive started having a very similar issue. Was working perfectly with Expo SDK 40 and react-navigation 5.

Upgraded to Expo SDK 42 (along with upgrading react-native-screens etc) and immediately started failing on android.

Behavior: Stack would render on initial load and work correctly, if I navigated away from the stack (my stacks are nested in a tab navigator) they would no longer render anything.

Switching to `createStackNavigator` instead of `createNativeStackNavigator` fixed the issue.

**Comment by kacperkapusciak** [comment]
@tevonsb could you open a new issue with a reproduction of your problem rather than commenting on this 2-year-old issue?

Cheers
