### ISSUE TITLE
Android - Bug from alpha.13 and higher - App is getting stucked

### ISSUE THREAD

**Issue by sebinq** [kmagiera/react-native-screens#271]
Hello there.

I've found a bug with react-native-screens on Android devices. Reproduce steps:

1. Run the app on android device.
2. Optionally you can try to change a screen in StackNavigator using Button first and you will see that Stack is working properly.
3. Change tab to 'Second Tab'.
4. Change tab back to 'First Tab'.
5. Try to change a screen in Stack using button.
6. The Background screen get pushed up but no new screen is displayed and the App is stucked at this point.

When I comment `enableScreens()` call or install `react-native-screen@alpha.12`, then everything is working properly.

I'm enclosing the demo video of the bug and repository with reproducible source code.

## Demo video

![screensbug](https://user-images.githubusercontent.com/33039909/71897708-992cfe80-3157-11ea-8f43-537e07336b72.gif)

## Link to reproducible demo

[reproducible demo](https://github.com/sebinq/react-native-screens-bug)

I've tried to track down the issue and following commit is potentionally causing the issue (but I'm not sure about that) [31192250e127b7c71dae41b08d6d571123206c3d](https://github.com/kmagiera/react-native-screens/commit/31192250e127b7c71dae41b08d6d571123206c3d)

Thank you so much!

**Comment by owinter86** [comment]
Hey @sebinq this is also reported in an earlier issue here https://github.com/kmagiera/react-native-screens/issues/259

**Comment by sebinq** [comment]
@owinter86 I'm sorry I missed that one.

**Comment by sebinq** [comment]
Closing in favour of #259
