### ISSUE TITLE
Touch events work in the last active Screen only

### ISSUE THREAD

**Issue by hssrrw** [kmagiera/react-native-screens#31]
I'm trying to experiment with the lib. The idea was to implement some kind of virtualized list detaching off-screen items. I noticed that touch components don't work inside Screen views but the last one. Is this intentional? Can I change this somehow?

It's probably not a good idea to attach/detach views on scroll anyway. Though, I see a few use cases where at least two screens could be active at the same time and would need to handle touch events.

Thank you for your amazing work ❤️

**Comment by brentvatne** [comment]
this is intentional. i don't think this use case makes sense for screens but can you post code? i'm curious to see

**Comment by hssrrw** [comment]
Well that was a stupid experiment while tinkering with the lib to understand some potential use cases other then using in navigation stack. Never mind 😃
