### ISSUE TITLE
Blank Screen 

### ISSUE THREAD

**Issue by punisher97** [kmagiera/react-native-screens#316]
Hi, i know currently exist multiple issues with this topic, but this issue ( as #106) its my own opinion while i build my custom navigation library using react-router, i testing and render many forms and methods to render the stack.

**Example Stack and navigation**: 

- *Go forward:* 
1)Login > 2)Register > 3)Terms And Conditions = **OK**

- *Go back:*
 **ERROR: Blank screen!** = 1)Login < 2)Register < 3)Terms And Conditions
(I used back button of native NavBar with Header Config Component)

## With Error (Blank Screen)

 
![blank_screen_error_blurgif](https://user-images.githubusercontent.com/8255332/74119493-9c1f7280-4b8d-11ea-80e0-6dc75d9d28fc.gif)

## Fixed:
![blank_screen_posible_solution_blur](https://user-images.githubusercontent.com/8255332/74119535-d0932e80-4b8d-11ea-90c1-40c6fbab8fb0.gif)
 
## To take into account

1. When 2)Register screen have stackAnimation="none" this fix the error :)

2. if in onDismissed callback delayed goBack to prevent re-render or dispatch new state while transtioning or animated screen.
 
## Posible javascript Solution for bare projects

````typescript
  // when screen dismissed (onDismissed callback)
  const onDismissed = async (ctx: ContextDismissAppear) => {
    setTimeout(()=>goBack(),1000);
  };
```` 

- Posible javascript Solution for Expo projects - (No testing) - check createNativeStackNavigator and add setTimeout in onDismissed callback

- Posible solution in native platform?

Thanks, Sorry my english

# Environment

react-router-native: 5.1.2,
react-native: 0.61.5
react-native-screens: 2.0.0-beta.2
Device info : iOS

**Comment by appify-waheed** [comment]
@punisher97 i have tried in IOS and it didn't works.

**Comment by punisher97** [comment]
> @punisher97 i have tried in IOS and it didn't works.

@appify-waheed Hi, you can setting stackAnimation="none" in previous screen?, in my example it's Register

**Comment by appify-waheed** [comment]
@punisher97 same after passing 
stackAnimation="none" 
may be i have some other issue.

**Comment by punisher97** [comment]
I replace native back button with custom back, thanks
