### ISSUE TITLE
iOS Modal close

### ISSUE THREAD

**Issue by DimitryDushkin** [kmagiera/react-native-screens#38]
I'm just opening within stack navigator (react-navigation) Modal from 'react-native' and it is not calling onRequestClose on swipe from left to right gesture, but it visually closes Modal. Without rn-screens it works.

**Comment by brentvatne** [comment]
hi! please provide a reproducible example, it is very hard to understand your exact scenario from one small paragraph, while it is trivial to understand what you mean by running a minimal example. create a new issue with it when you have a chance, thanks!
