### ISSUE TITLE
Unable to paste into TextInput

### ISSUE THREAD

**Issue by cmcewen** [kmagiera/react-native-screens#40]
I just got this library set up and running, but when testing I find I'm unable to paste into TextInputs on Android. Not calling `useScreens` in my initialization fixes this issue.

**Comment by jamsch** [comment]
@cmcewen Seems to be an issue with RN. I posted a workaround in the thread.
https://github.com/facebook/react-native/issues/20887

**Comment by kmagiera** [comment]
hey @cmcewen can you provide some more details regarding your setup here? That is android version react-native version, version of the screens library and anything that you'd think is relevant. We'd like to approach this problem somehow but it is difficult without a reliable way of reproducing it.

**Comment by evanjmg** [comment]
There's an issue with pasting rich content into textInputs - if I paste an image it crashes the app

**Comment by osdnk** [comment]
This issue appears to be resolved since the problem probably comes from RN core. If you still face the problem, please let me know.

**Comment by diegolmello** [comment]
@osdnk I'm still facing this error.
Everything seems to work fine on RN itself, but it stops working when react-native-screen is added.

I've created this reproducible repo:
https://github.com/diegolmello/PasteExample

It's a simple demo on top of latest RN version with few packages added:
```json
"react-native": "0.61.3",
"react-native-gesture-handler": "^1.5.0",
"react-native-reanimated": "^1.3.2",
"react-native-screens": "^2.0.0-alpha.7",
"react-navigation": "^4.0.10",
"react-navigation-stack": "^1.10.3"
```

The important part is that when `enableScreens()` is commented everything works: https://github.com/diegolmello/PasteExample/blob/master/App.js#L9

Let me know if I can help in any way.
Thank you.

**Comment by compojoom** [comment]
@osdnk - please reopen the issue. The problem is still there on RN 0.61.3 and @diegolmello has provided a reproducible demo.

**Comment by wong2** [comment]
I'm still having the issue

**Comment by kmagiera** [comment]
Thanks all for contributing to the discussion here. Can you please confirm if this is the same problem as reported in #205? If so let's move the discussion there and keep this issue closed.

**Comment by aneequeahmad** [comment]
@kmagiera the issue is still reproducible in the latest RN version. Actually the problem is only with `Android` selecting text in `TextInput` isn't showing the context menu most of the times. It seems like the problem is with `onSelectionChange` function as selecting the text causes the cursor to flicker and because of this the component re-renders and context menu is closed.
