### ISSUE TITLE
Call willMoveToWindow before navigating with react-navaigation

### ISSUE THREAD

**Issue by tychota** [kmagiera/react-native-screens#44]
(discussion happened offline with @kmagiera)
ccing @brentvatne as it will probably require changes in react-navigation.

On my project, we had a bug with react-native `<InputAccesoryView />`:

![dec-06-2018 15-50-29](https://user-images.githubusercontent.com/13785185/49591464-d3353b00-f96e-11e8-834d-ca150bdef819.gif)

After investigating with @chdeps, we decided to patch rn and using the nice hooks that react-native-screens give us:

```diff
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import "RCTInputAccessoryView.h"

#import <React/RCTBridge.h>
#import <React/RCTTouchHandler.h>
#import <React/UIView+React.h>

#import "RCTInputAccessoryViewContent.h"

@interface RCTInputAccessoryView()

// Overriding `inputAccessoryView` to `readwrite`.
@property (nonatomic, readwrite, retain) UIView *inputAccessoryView;

@end

@implementation RCTInputAccessoryView
{
  BOOL _shouldBecomeFirstResponder;
}

  - (instancetype)initWithBridge:(RCTBridge *)bridge
  {
    if (self = [super init]) {
      _inputAccessoryView = [RCTInputAccessoryViewContent new];
      RCTTouchHandler *const touchHandler = [[RCTTouchHandler alloc] initWithBridge:bridge];
      [touchHandler attachToView:_inputAccessoryView];
    }
    return self;
  }

  - (BOOL)canBecomeFirstResponder
  {
    return true;
  }

  - (void)reactSetFrame:(CGRect)frame
  {
    [_inputAccessoryView reactSetFrame:frame];

    if (_shouldBecomeFirstResponder) {
      _shouldBecomeFirstResponder = NO;
      [self becomeFirstResponder];
    }
  }

+  - (void)didMoveToWindow {
+    [super didMoveToWindow];
+    BOOL isVisible = self.superview && self.window;
+    
+    if (isVisible) {
+      [self becomeFirstResponder];
+    } else {
+      [self resignFirstResponder];
+    }
+  }

  - (void)insertReactSubview:(UIView *)subview atIndex:(NSInteger)index
  {
    [super insertReactSubview:subview atIndex:index];
    [_inputAccessoryView insertReactSubview:subview atIndex:index];
  }

  - (void)removeReactSubview:(UIView *)subview
  {
    [super removeReactSubview:subview];
    [_inputAccessoryView removeReactSubview:subview];
  }

  - (void)didUpdateReactSubviews
  {
    // Do nothing, as subviews are managed by `insertReactSubview:atIndex:`.
  }

  - (void)didSetProps:(NSArray<NSString *> *)changedProps
  {
    // If the accessory view is not linked to a text input via nativeID, assume it is
    // a standalone component that should get focus whenever it is rendered.
    if (![changedProps containsObject:@"nativeID"] && !self.nativeID) {
      _shouldBecomeFirstResponder = YES;
    }
  }

@end
```

That worked well:

![dec-06-2018 15-30-50](https://user-images.githubusercontent.com/13785185/49591735-90279780-f96f-11e8-9f37-b9f04da48711.gif)

But the actually the <InputAccesoryView /> stays too long. We tryed to do:

```diff
#import "RCTInputAccessoryView.h"

#import <React/RCTBridge.h>
#import <React/RCTTouchHandler.h>
#import <React/UIView+React.h>

#import "RCTInputAccessoryViewContent.h"

@interface RCTInputAccessoryView()

// Overriding `inputAccessoryView` to `readwrite`.
@property (nonatomic, readwrite, retain) UIView *inputAccessoryView;

@end

@implementation RCTInputAccessoryView
{
  BOOL _shouldBecomeFirstResponder;
}

/// .....

+  - (void)didMoveToWindow {
+    [super didMoveToWindow];
+    BOOL isVisible = self.superview && self.window;
+    
+    if (isVisible) {
+      [self becomeFirstResponder];
+    } else {
+      [self resignFirstResponder];
+    }
+  }

+  - (void)willMoveToWindow:newWindow {
+    [super didMoveToWindow:newWindow];
+    [self resignFirstResponder];
+  }

/// .....

@end
```

But still the problem.

IOS dev are calling `willMoveToWindow` before navigation and `didMoveToWindow` after/
React navigation isn't thus it make it hard to use the `willMoveToWindow` usefully.

**Comment by kmagiera** [comment]
It appears that the way this is normally handled on iOS is by using `willMoveToWindow` and/or `didMoveToWindow`

When using `UINavController`, `willMoveToWindow` triggers with `nil` window when the animation starts. What happens under the hood is that `UINavController` then immediately remounts the view and only unmounts it when the animation is over.

I went ahead and attempted to implement that behavior in `ScreenContainer` (apparently we can't use `UINavController` directly for reasons). If you have some time please try it from my branch here:  https://github.com/kmagiera/react-native-screens/tree/move_window_events

The patch is here -> https://github.com/kmagiera/react-native-screens/compare/master...move_window_events

**Comment by tychota** [comment]
I made a minimal working example here: https://github.com/tychota/BugInputAcessoryView

- My bug: https://github.com/tychota/BugInputAcessoryView/tree/master
- The fix of the biggest bug, thanks to RN : https://github.com/tychota/BugInputAcessoryView/pull/2
- The try to fix the bug with the patch of @kmagiera : https://github.com/tychota/BugInputAcessoryView/pull/1 (sadly not working)

**Comment by tychota** [comment]
> I went ahead and attempted to implement that behavior in ScreenContainer (apparently we can't use UINavController directly for reasons). If you have some time please try it from my branch here: https://github.com/kmagiera/react-native-screens/tree/move_window_events

Can you detail a bit the reason ? Too much teasing for my curiosity :)

**Comment by kmagiera** [comment]
Closing this as of #47 – the updated version will be published soon. Please try it out and reopen if the problem persist

**Comment by tychota** [comment]
I will definitivly try. Thank you sir.

**Comment by ZakSingh** [comment]
Was a fix for this released? I'm having a bit of trouble following the convo here (I don't know anything about native dev). We're experiencing the exact same problem with the InputAccessoryView rendering a second or so after the screen transition ends. It works ok in regular react-navigation v5, so that's a fallback for now, but it would be great if we could use react-native-screens instead!
