### ISSUE TITLE
Screen unresponsive to touch when using tab navigator

### ISSUE THREAD

**Issue by truted** [kmagiera/react-native-screens#53]
Sorry, but my project is quite complicated so I can't isolate a test case.

I noticed that when upgrading from alpha.16 to alpha.19, the screen becomes unresponsive to touch when tabbing between views using the tab navigator on iOS. After toggling through several tabs the screen once again becomes responsive. Each of my tab navigators has nested stack navigators (not sure if that's relevant) 

Hope this helps uncover an issue.

**Comment by hanse** [comment]
I've been experiencing this as well when using react-native-screens and react-navigation TabNavigator. I'm also using react-native-gesture-handler for buttons but as the screencast below shows it also happens with `TouchableOpacity` as well.

Here is a minimal reproduction of the bug w/ screencast: https://github.com/hanse/screens-bug-repro. By commenting out `useScreens` it works as intended.

Merry Christmas!  🎄🎅🏻

**Comment by noahtallen** [comment]
I also noticed this issue in a largeish app when updating to 3.x react navigation. I installed the gesture handler library as well as react native screens to check it out, but immediately noticed the app freezing pretty frequently while switching between views. I have a stack nav containing a tab navigator where each screen is a react component, and the rest of the sub-screens are in the top-level stack navigator. Opting out of react screens seems to fix the issue. This happens in both development and release versions.

I’m really excited for this library to work more stably, because it’s going to boost android experience a ton!

**Comment by nitaking** [comment]
I am totally the same phenomenon.
Comment out useScreen to erase it.
https://github.com/react-navigation/react-navigation-tabs/issues/83

**Comment by sivakumar-cf** [comment]
I am also facing the same issue.

**Comment by reneeichhorn** [comment]
I'm facing this since I enabled `react-native-screens` as well. Whats weird is that it happens on a single tab only for me. I have some similar tabs that never broke so far even though they have almost the same content. (They all have TouchableOpacity components everywhere..)

**Comment by shawnthye** [comment]
I am using 1.0.0-alpha.17 now , had issue with `alpha.17`
here is my dependencies

```

  "dependencies": {
    "react": "16.6.3",
    "react-native": "0.57.8",
    "react-native-gesture-handler": "^1.0.12",
    "react-native-screens": "1.0.0-alpha.17",
    "react-navigation": "3.0.9"
  },
  "resolutions": {
    "**/react-native-screens": "1.0.0-alpha.17"
  },
```

**Comment by kmagiera** [comment]
Thank you all for reporting and especially @hanse for coming up with a repro app – it was very helpful!

I managed to locate a bug, fixed it and published alpha.21 with the fix included. Please try it out and let me know if you still experience the issue

**Comment by tgensol** [comment]
Looks like it is working well now with your fix, thank you !

**Comment by townmulti** [comment]
@kmagiera This is still going on in alpha.21. Here's is a snack: [expo-snack](https://snack.expo.io/@multitown/react-native-screens-freeze)

To test, I just continually switch tabs, check for scrolling and soon a tab screen will become unresponsive. However, I could only duplicate this on the physical device.

**Comment by kmagiera** [comment]
@townmulti The fix required native code changes so if you are using expo it isn't sufficient to install javascript bit via npm. I'll talk with expo and ask if they could pull in native code changes. In the meantime if you have a standalone RN app you can try it there and see if the problem still persist

**Comment by kmagiera** [comment]
actually got an info from @tsapeta that native changes from alpha.21 will be included in the next expo patch release that is already in review and should be available soon

**Comment by townmulti** [comment]
@kmagiera @tgensol thanks! ...will test it again after update!

**Comment by mvayngrib** [comment]
issue is still present, re-opened [here](https://github.com/kmagiera/react-native-screens/issues/102) with easy repro snack

**Comment by bcgilliom** [comment]
Happening for me on alpha-23 with react-navigation 3.11 with a custom tab navigator that keeps multiple `Screen`s active (so the animation can show)

**Comment by bhattanmol101** [comment]
I am still facing this issue but I am not using useScreens from react-native-screens anywhere in my project
Facing this issue on react-navigation v5

**Comment by thife455** [comment]
@bhattanmol101 have you managed to find a solution? This bug is driving me crazy!

**Comment by nitrocrete** [comment]
bump

**Comment by bhattanmol101** [comment]
I don't know if it's a solution or not but this is what I did.

I read the above comments that `useScreens` should not be used or should be false but I was not using `useScreens` function at all anywhere in my code but I had that react-native-screens dependency in my package.json.

Also, the `useScreens` function has been deprecated in the recent version so after searching a little bit the `useScreens` function has been renamed to `enableScreens` function.

As the above comment said that `useScreens` should be false I used `enableScreens(false)` in my App.js before defining the class but that didn't work, much to my surprise writing `enableScreens(true)` made it work. I don't know what is the real issue but with `enableScreens(true)` it worked.

The below screenshot shows how I have used it in my App component. App component renders just the stack navigator in which one of the routes has bottom tabs in it, so as soon as the user logs in it goes to tab navigation.

<img width="582" alt="Screen Shot 2021-01-26 at 1 27 42 PM" src="https://user-images.githubusercontent.com/27304378/105816427-4cbe9600-5fda-11eb-8dee-4aef55d9b69d.png">

**Comment by noodlesftw** [comment]
@bhattanmol101's solution worked for me.

**Comment by AlenToma** [comment]
Nothing works for me

**Comment by sujon54** [comment]
Thanks, @bhattanmol101 your solution worked for me.

**Comment by vortexflame1404** [comment]
@bhattanmol101 Thanks this works for me

**Comment by Payhemfoh** [comment]
@bhattanmol101  Thanks, your solution is worked for me also.

**Comment by omerts** [comment]
I also had this issue, updating all the dependencies of react-navigation to latest version solved it for me

**Comment by IssueResolver-collab** [comment]
This fix will bring back all touch and scroll events back but will create problem if you have tabBarIcon with position:absolute then it will not overflow the tab bar, instead it will get cut off

**Comment by yepMad** [comment]
This keeps happening in newer versions.

**Comment by AlenToma** [comment]
I had this problem before, in my case it was that I had a WebView component in Navigation screen that caused the problem.

**Comment by dlipahir** [comment]
> in latest version, there is no `useScreens` and `enableScreens` does not work for me. This problem keeps happening. any solutions or workaround?

I uninstall the app after adding "enablescreens(true)" and then start again
worked for me in android

**Comment by manosKas** [comment]
> I had a WebView component in Navigation screen

@AlenToma what do you mean exactly? everything must go inside the nagivation context, withing screens

i have a horizontal paging list where each item is a webview (like gmail app)
