### ISSUE TITLE
Unable to resolve path to module 'react-native-screens' (ESLint)

### ISSUE THREAD

**Issue by gsklee** [kmagiera/react-native-screens#62]
Got this lint error in my VS Code:

```
Unable to resolve path to module 'react-native-screens'.eslint(import/no-unresolved)
module "react-native-screens"
```

**Comment by noahtallen** [comment]
Assuming you've run `npm install`? lol

**Comment by CodyBrouwers** [comment]
I get this error as well, looking in the `react-native-screens` folder in my `node_modules`, if I add an `node_modules/react-native-screens/index.js` file with the following, the ESLint error goes away:

```js
import screens from './src/screens';

export default screens;
```

**Comment by blankonn** [comment]
happen to me as well, for now I disabled that error by using `// eslint-disable-next-line import/no-unresolved`

**Comment by AChevallier** [comment]
Same problem for me :( 
Annoying !

**Comment by skleeschulte** [comment]
I fixed this issue by adding the extension `.native.js` to the [eslint-import-resolver-node](https://www.npmjs.com/package/eslint-import-resolver-node) config in my .eslintrc file:

```
{
  "parser": "babel-eslint",
  "extends": "airbnb",
  "settings": {
    "import/resolver": {
      "node": {
        "extensions": [".js", ".jsx", ".json", ".native.js"]
      }
    }
  }
}
```

Explanation: The idea comes from [benmosher's comment at eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import/issues/279#issuecomment-215052176). In my case, `[".js", ".jsx", ".json"]` is the default configuration for the node resolver extensions; this can be found out e.g. by running `eslint --print-config index.js`. (The eslint-import-resolver-node extensions for the default airbnb config are defined in [eslint-config-airbnb/rules/react.js](https://github.com/airbnb/javascript/blob/eslint-config-airbnb-v17.1.0/packages/eslint-config-airbnb/rules/react.js#L459) as `['.js', '.jsx', '.json']`; eslint-config-airbnb [adds rules for React by default](https://github.com/airbnb/javascript/tree/eslint-config-airbnb-v17.1.0/packages/eslint-config-airbnb#eslint-config-airbnb-1): [eslint-config-airbnb/index.js](https://github.com/airbnb/javascript/blob/eslint-config-airbnb-v17.1.0/packages/eslint-config-airbnb/index.js).) react-native-screens [sets src/screens as main entry point in the package.json file](https://github.com/kmagiera/react-native-screens/blob/1.0.0-alpha.22/package.json#L13). In the [src-folder](https://github.com/kmagiera/react-native-screens/tree/1.0.0-alpha.22/src) [screens.native.js](https://github.com/kmagiera/react-native-screens/blob/1.0.0-alpha.22/src/screens.native.js) is the correct entry point for react-native, so adding `.native.js` to the list of resolver extensions fixes the problem.

**Comment by troydaniels** [comment]
Thanks @skleeschulte!
Can confirm that this works for us as well.

**Comment by mi-mazouz** [comment]
not working for me

**Comment by Jahanzai6** [comment]
I resolve that error by simply 
npm install react-native-screens

**Comment by tapz** [comment]
After adding the settings to .eslintrc the error changed to this:

> enableScreens not found in 'react-native-screens' eslint(import/named)

**Comment by Frends23** [comment]
also resolve with
yarn add react-native-screens

**Comment by olliefinn** [comment]
I tried all of the options outlined here (and elsewhere) and had no luck. What has seemed to resolve the issue was to add the following to the `.flowconfig` file
```
module.file_ext=.native.js
```
