### ISSUE TITLE
Keyboard is not attached to native navigation container

### ISSUE THREAD

**Issue by thorbenandresen** [kmagiera/react-native-screens#63]
I am not sure if this is intended behavior, but I expected the keyboard to be attached to the native navigation container like this:

**Expected (gif showing `react-native-navigation` with slow animations enabled)**
[![Image from Gyazo](https://i.gyazo.com/e40f7e20cb6c51ed937781d7c456fcba.gif)](https://gyazo.com/e40f7e20cb6c51ed937781d7c456fcba)

**Actual (gif showing`react-navigation` with `useScreens()` with slow animations enabled)**
[![Image from Gyazo](https://i.gyazo.com/7003482faa95c16b38089bf07dde3748.gif)](https://gyazo.com/7003482faa95c16b38089bf07dde3748)

```
"expo": "^32.0.0",
"react": "16.5.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
"react-native-screens": "^1.0.0-alpha.22",
"react-navigation": "^3.0.9"
```

Source: https://github.com/Thorbenandresen/react-native-screens-test

**Comment by pyankoff** [comment]
Having some weird keyboard behavior when enabling Screens. Keyboard doesn't dismiss after navigating to another screen and back. Even on `Keyboard.dismiss()` call. It seems like without Screens keyboard is dismissed on every navigation.

Should I create a different issue?

**Comment by brentvatne** [comment]
@pyankoff - create a minimal repro and post a new issue

animating keyboard with screen - probably not going to do this but you're welcome to open a pr for it
