### ISSUE TITLE
Add tvOS Static Library Build Target to Support tvOS

### ISSUE THREAD

**Issue by hufkens** [kmagiera/react-native-screens#64]
Can you add a new tvOS Static Library build target for this package?

I found an example on how to do this in another library: https://github.com/react-native-community/react-native-video/pull/614/commits/bed60891765c7127eec6740f5e00b552f2cf8b95

**Comment by hufkens** [comment]
@kmagiera I created a PT https://github.com/kmagiera/react-native-screens/pull/65

**Comment by kmagiera** [comment]
Thanks a lot @hufkens! Closing this as just merged #65
