### ISSUE TITLE
Keyboard not dismissing

### ISSUE THREAD

**Issue by pyankoff** [kmagiera/react-native-screens#67]
Having some weird keyboard behavior when enabling Screens. Keyboard doesn't dismiss after navigating to another screen and back. Even on `Keyboard.dismiss()` call. It seems like without Screens keyboard is dismissed on every navigation.

Repo: https://snack.expo.io/@andrey/keyboard-bug
Focus TextInput -> Next Screen -> Back -> Keyboard is not dismissing

**Comment by osdnk** [comment]
Conform to reproduce it only on iOS

**Comment by osdnk** [comment]
I hope i fixed it 😃
