### ISSUE TITLE
Question: Integration with TabNavigator?

### ISSUE THREAD

**Issue by scottmas** [kmagiera/react-native-screens#73]
So this library has been integrated with React Navigation StackNavigator. But it seems like it would make sense to integrate it with TabNavigator as well to detach non-visible tabs from the view hierarchy. 

Is this feasible? Are there plans to do it? Would there be unforeseen side effects?

Thanks!

**Comment by brentvatne** [comment]
this happens already with tabnavigator automatically. you can see the implementation in https://github.com/react-navigation/react-navigation-tabs/blob/master/src/views/ResourceSavingScene.js

**Comment by scottmas** [comment]
Cool thanks!
