### ISSUE TITLE
useScreens() and transparentCard issue

### ISSUE THREAD

**Issue by ovy9086** [kmagiera/react-native-screens#79]
When using react-native-screens with react-navigation 3 , enabling both `useScreens()` and `transparentCard` in the `createStackNavigator` options causes weird issues.

On iOS, if having more than 3 routes in the StackNavigator, when going back to the 2nd screen, you will not be able to interact the view anymore. Apparently something blocks it.
On Android, the 2nd screen is not clickable from the first time you navigate to it.

Here is a repo to reproduce this : https://github.com/ovy9086/react-nav-transparent-card-bug

**Comment by brentvatne** [comment]
closed because dup

**Comment by elan** [comment]
Running into this one as well.

**Comment by brentvatne** [comment]
@elan 

https://github.com/kmagiera/react-native-screens/issues/71
https://github.com/kmagiera/react-native-screens/issues/71
